### ISSUE TITLE
Use the non-finetuned LLaMA-2-7B as the news encoder to train GENRE

### ISSUE THREAD

**Issue by Forvever0827** [Jyonn/GENRE-requests#11]
Hi,

I am trying to run experiments by Using the non-finetuned LLaMA-2-7B as the news encoder to train GENRE Could you direct me to any of the existing configurations or give some suggestions on how to set the parameters of the configurations?

Thank you!

**Comment by Jyonn** [comment]
Hi, for now Legommenders only support LLaMA-1, not LLaMA-2, due to the layer cache feature used is implemented on an old version of `transformers` package.

However, in your scenario where the Llama is not required to be finetuned. It can be implemented in this way:

1. Extract each item representations by Llama-2 and save them into a numpy file (a R^{N x d} tensor). You should write this script by your own. Note that, if you use our processed data such as MIND, Goodreads, or Adressa, the order of items should follow `tok.<item_id>.dat` file. 

2. Create an embed config file, here is an example:
```yaml
name: llama2-item
embeddings:
  -
    vocab_name: nid
    vocab_type: numpy
    path: data/${data.name}/news-llama2.npy
    frozen: ${frozen}$
```

3. Run the recommender with:

```bash
python worker.py --data config/data/mind.yaml --model config/data/lego_naml_rl.yaml --embed config/embed/<your-embed-config>.yaml --batch_size 256 --lr 0.001 --frozen 1 --embed_batch_size 4096
```

In this case, the news encoder is decoupled with the user encoder and the prediction module. 

Several Tips:
- This issue is better to be posted on the Legommenders repo.
- Legommenders support the multiple-embedding-initialization. It means, you can cache several layer output for each item, and form a R^{N x L x d} tensor to the numpy file. Please refer [here](https://github.com/Jyonn/Legommenders/blob/master/loader/embedding/embedding_hub.py), the TransformMultiEmbedding class, for the related code implementation.
- Our Legommenders V2 is coming, which supports more LLM transformers with simpler configuration, also includes your case. Before that, please ensure that your unitok version is less than 4.x: `pip install unitok==3.5.3`.

**Comment by Forvever0827** [comment]
Thank you for replying so late. I will also post this question in the Legommenders repo。

At the same time, I have some questions when using llama-1-7b to fine tune layer 0 and reproduce DIRE. Please use the instructions you provided
`python worker.py --data config/data/mind-llama.yaml --embed config/embed/<embed>.yaml --model config/model/bert-<basemodel>.yaml --exp config/exp/tt-llm.yaml --embed_hidden_size <embed_hidden_size> --llm_ver <llm_ver> --layer <layer> --version small --lr 0.0001 --item_lr 0.00001 --batch_size 32 --acc_batch 2 --epoch_batch -4`

I use the following command: 
`python  worker.py --data config/data/mind-llama.yaml --embed config/embed/llama-token.yaml --model config/model/llm/llama-naml.yaml --exp config/exp/tt-llm.yaml --embed_hidden_size 4096 --llm_ver 7b --layer 31 --version small --lr 0.0001 --item_lr 0.00001 --batch_size 32 --acc_batch 2 --epoch_batch -4 `
The reference is the content of the example in the Legommenders repo, but the final model performance differs greatly from Table 3. Is it a problem with my parameter settings.
You mentioned in your paper: During training, we employ Adam [15]  optimizer with a learning rate of 1e-3 for the MIND dataset and  1e-4 for the Goodreads dataset. If the large language models are not  tuned with LoRA [13], their learning rates are set to 1e-5， But I didn't fine tune Llama. The learning rate should have been set to 0.00001, but it still hasn't had a good effect. How should I set my parameters?

My configuration file settings are as follows:
mind-llama.yaml

```
name: MIND-${version}-Llama
base_dir: data
item:
  filter_cache: true
  depot: ${data.base_dir}/news-llama
  order:
    - title
    - cat
  append:
    - nid
user:
  filter_cache: true
  depots:
    train:
      path: ${data.base_dir}/train
    dev:
      path: ${data.base_dir}/dev
    test:
      path: ${data.base_dir}/test
  filters:
    history:
      - x
  union:
    - ${data.base_dir}/user
    - ${data.base_dir}/neg
  candidate_col: nid
  clicks_col: history
  label_col: click
  neg_col: neg
  group_col: imp
  user_col: uid
  index_col: index
  # plugin: ${data.base_dir}/user-plugin
  # plugin_cols:
  #   - topics
    # - news_pad    #代码中是对于每条行为进行预测还是每个用户
```
llama-token.yaml

```
name: llama-token
embeddings:
  -
    vocab_name: llama
    vocab_type: numpy
    path: data/llama-token.npy
    frozen: true
```

tt-llm.yaml

```
name: ${exp.mode}
dir: saving/${data.name}/${model.name}/${embed.name}-${exp.name}
log: ${exp.dir}/exp.log
mode: train_test
load:
  save_dir: ${load_path}$
  epochs: null
  model_only: true
  strict: false
  wait: false
store:
  metric: GAUC
  maximize: true
  top: 1
  early_stop: ${patience}$
policy:
  epoch_start: ${epoch_start}$
  epoch: 50
  lr: ${lr}$
  item_lr: ${item_lr}$
  freeze_emb: false
  pin_memory: false
  epoch_batch: ${epoch_batch}$
  batch_size: ${batch_size}$
  accumulate_batch: ${acc_batch}$
  device: gpu
  n_warmup: ${warmup}$
  check_interval: -2
  simple_dev: ${simple_dev}$
metrics:
  - GAUC
  - MRR
  - NDCG@1
  - NDCG@5
  - NDCG@10
```

llama-nrms.yaml

```
name: LLAMA-NRMS.D${model.config.hidden_size}.L${model.config.item_config.layer_split}.Lora${model.config.item_config.lora}
meta:
  item: Llama
  user: Attention
  predictor: Dot
config:
  use_neg_sampling: true
  use_item_content: true
  max_item_content_batch_size: 0
  same_dim_transform: false
  embed_hidden_size: ${embed_hidden_size}$
  hidden_size: ${hidden_size}$
  neg_count: 4
  item_config:
    llm_dir: /root/autodl-tmp/llama/7bHF
    layer_split: ${layer}$
    lora: ${lora}$
    weights_dir: /root/autodl-tmp/data_all/MIND-small-Llama/llama-7b-split
  user_config:
    num_attention_heads: 8
    inputer_config:
      use_cls_token: false
      use_sep_token: false
```
Sorry, my reply was quite lengthy and took up your time.

**Comment by Jyonn** [comment]
Hi, it seems you would like to freeze the entire Llama-1-7B model in this experiment.

I would like to double check your layer split process, which should be runned before model training, to cache the output hidden states of all items. In this process, which command do you use? The suggested command is:
```
python worker.py --embed config/embed/<embed>.yaml --model config/model/llama-naml.yaml --exp config/exp/llama-split.yaml --data config/data/mind-llama.yaml --version small --llm_ver <llm_ver> --hidden_size 64 --layer 0 --lora 0 --fast_eval 0 --embed_hidden_size <embed_hidden_size>
```
where --embed should be specifically set to your llama-token.yaml.

You can ignore the `--item_lr` parameter or set it to any number, since the LM-transformer network will not be detected in this case.

I would also want to check your used columns,
```yaml
  depot: ${data.base_dir}/news-llama
  order:
    - title
    - cat
```

If you use our processed data, you should set the data config to 
```yaml
order:
  - title-llama
  - cat-llama
lm_col: title-llama
```

for both llama-split exp and tt-llm exp.

**Comment by Jyonn** [comment]
You should ensure that the input item features are tokenized with llama-1 tokenizer.

**Comment by Jyonn** [comment]
I would also like to clarify that the following two settings:

- use layer-split to cache the output hidden states for all items in Llama-1 -> produce N x S x d tensor, S represents the item content length
- customize a script to extract item embeddings with Llama-2 -> produce N x d tensor

are not fair for comparison (maybe acceptable), because in the first case, an additive attention layer is used to fuse hidden states with S length to a unified item representation in d dimension during training.

If you would like to use Llama-2 to replace Llama-1 in DIRE settings, you should write a script to produce output hidden states (r^S x d), rather than the mean pooling of the states to form the item embedding (R^d), and replace the weights for experiments.

**Comment by Forvever0827** [comment]
Hello, thank you for your reply. I used the following instructions during the layer split process:
`python worker.py --embed config/embed/llama-token.yaml --model config/model/llm/llama-nrms.yaml --exp config/exp/llama-split.yaml --data config/data/mind-llama.yaml --version small --llm_ver 7b  --layer 0 --lora 0 --embed_hidden_size 4096`
I use code
```
from transformers import LlamaModel, LlamaTokenizer
import torch
import numpy as np
#Load pre trained LLaMA model and tokenizer
model_name = '/root/autodl-tmp/llama/7bHF'
model = LlamaModel.from_pretrained(model_name)
tokenizer = LlamaTokenizer.from_pretrained(model_name)
#Extract weights from embedded layers
embedding_weights = model.embed_tokens.weight.detach().cpu().numpy()
#Save embedding layer weights to. npy file
np.save('data/llama-token.npy', embedding_weights)
```
Obtained llama-token.py file
Excuse me, is there any problem with this?
For the setting of the learning rate, I would like to ask if for llama-1-7b as a news encoder, the learning rate should be set to 0.001 and the use of -- acc_datch 2-epoch_datch -4 is required

**Comment by Jyonn** [comment]
your extraction code is perfect. 

they can be customized to other values.

acc_batch can be set to 1, if your GPU memory allows a larger batch size.
epoch_batch is default to 1, -4 represents that the current epoch will only be trained with one fourth of the shuffled data.

**Comment by Forvever0827** [comment]
Thank you very much for your reply,I would like to kindly ask you again to help me check my configuration. I still have some questions.
Based on your guidance, I used llama-1-7b to reproduce the fine tuned 0-layer NRMS model. The data is yours, and my cached data should be fine. However, the results I reproduced seem to differ significantly from Table 3 in your paper. Could you please check if there is a configuration error on my part

mind-llama.yaml
```
name: MIND-${version}-Llama
base_dir: ONCE/MIND-${version}
item:
  filter_cache: true
  depot: ${data.base_dir}/news
  order:
    - title-llama
    - cat-llama
  append:
    - nid
  lm_col: title-llama
user:
  filter_cache: true
  depots:
    train:
      path: ${data.base_dir}/train
    dev:
      path: ${data.base_dir}/dev
    test:
      path: ${data.base_dir}/test
  filters:
    history:
      - x
  union:
    - ${data.base_dir}/user
  candidate_col: nid
  clicks_col: history
  label_col: click
  neg_col: neg
  group_col: imp
  user_col: uid
  index_col: index
```

llama-token.yaml
```
name: llama-token
embeddings:
  -
    vocab_name: llama
    vocab_type: numpy
    path: ONCE/llama-token.npy
    frozen: true
```

```
name: ${exp.mode}
dir: saving/${data.name}/${model.name}/${embed.name}-${exp.name}
log: ${exp.dir}/exp.log
mode: train_test
load:
  save_dir: ${load_path}$
  epochs: null
  model_only: true
  strict: false
  wait: false
store:
  metric: GAUC
  maximize: true
  top: 1
  early_stop: ${patience}$
policy:
  epoch_start: ${epoch_start}$
  epoch: 50
  lr: ${lr}$
  item_lr: ${item_lr}$
  freeze_emb: true
  pin_memory: false
  epoch_batch: ${epoch_batch}$
  batch_size: ${batch_size}$
  accumulate_batch: ${acc_batch}$
  device: gpu
  n_warmup: ${warmup}$
  check_interval: -2
  simple_dev: ${simple_dev}$
metrics:
  - GAUC
  - MRR
  - NDCG@1
  - NDCG@5
  - NDCG@10
```

```
name: LLAMA-NRMS.D${model.config.hidden_size}.L${model.config.item_config.layer_split}.Lora${model.config.item_config.lora}
meta:
  item: Llama
  user: Attention
  predictor: Dot
config:

  use_item_content: true
  use_neg_sampling: true
  max_item_content_batch_size: 0
  same_dim_transform: false
  embed_hidden_size: ${embed_hidden_size}$
  hidden_size: ${hidden_size}$
  neg_count: 4
  item_config:
    llm_dir: /root/autodl-tmp/llama/7bHF
    layer_split: ${layer}$
    lora: ${lora}$
    weights_dir: /root/autodl-tmp/data_all1/MIND-small-Llama/llama-7b-split
  user_config:
    num_attention_heads: 8
    inputer_config:
      use_cls_token: false
      use_sep_token: false
```

My instructions are as follows:
`python worker.py --data config/data/mind-llama.yaml --version small --model config/model/llm/llama-nrms.yaml --embed config/embed/llama-token.yaml --exp config/exp/tt-llm.yaml --lora 0 --item_lr 0 --lr 0.001 --batch_size 32 --embed_hidden_size 4096  --llm_ver 7b --layer 31`

my result:
[00:15:02] |Worker| GAUC: 0.6016
[00:15:02] |Worker| MRR: 0.2843
[00:15:02] |Worker| NDCG@1: 0.1312
[00:15:02] |Worker| NDCG@5: 0.2905
[00:15:02] |Worker| NDCG@10: 0.3567

**Comment by Forvever0827** [comment]
I'm very sorry, the last two code blocks are tt-llm.yaml and llama-nrms.yaml

**Comment by Jyonn** [comment]
Hi the configuration for tt-llm exp seems good.

Do you re-generate the item cache when switching title to title-llama in layer-split experiment?

**Comment by Forvever0827** [comment]
I directly generated  the item cache using title-llama and no use title.May I ask if this is possible？

**Comment by Forvever0827** [comment]
If I set the learning rate to 1e-4, the result is as follows:

[00:05:46] |Worker| [epoch 0] GAUC 0.6774
[00:09:53] |Worker| [epoch 1] GAUC 0.6676
[00:13:51] |Worker| [epoch 2] GAUC 0.6717

[00:15:32] |Worker| GAUC: 0.6746
[00:15:32] |Worker| MRR: 0.3442
[00:15:32] |Worker| NDCG@1: 0.1978
[00:15:32] |Worker| NDCG@5: 0.3593
[00:15:32] |Worker| NDCG@10: 0.4211

The data in Table 3 of your paper is still slightly lacking, but it is better than when the learning rate is 1e-3. Is there a problem with my learning rate and other parameter settings? May I ask you about the experimental parameters at that time?

**Comment by Jyonn** [comment]
Hi it seems all your configurations work well. I cannot find my original logs. The experiments are conducted over one year ago. It is possible for me to tune the model with learning rate from 1e-4 to 1e-3 for non-LLM parameters, and a learning rate for pretrained LLM parameters (i.e., item_lr) from 1e-6 to 1e-5/4. 

I just checked the implementation details in our paper, and here is a sentence `We tune the hyperparameters of all base models to attain optimal performance.` Sorry for the confusion! However, based on my memory, setting the learning rate for non-LLM parameters to 1e-3 achieves the best performance at the most of the time.

Yes, title is not needed when using Llama as news encoder.

**Comment by Forvever0827** [comment]
Okay, thank you very much for replying so late. I'll give it a try.
I wish you a happy New Year's Eve tomorrow

**Comment by Forvever0827** [comment]
sorry,I'm a bit confused about mind-llama.yaml

```
item:
  filter_cache: true
  depot: ${data.base_dir}/news
  order:
    - title-llama
    - cat-llama
  append:
    - nid
  lm_col: title-llama
```
If ABS is not used in this part, will ABS be used in the subsequent code？
